### ISSUE TITLE
The best Online FM Radio Player!

### ISSUE THREAD

**Issue by lovebdsobuj** [NamelessOne/FantasyRadio#1]
Can you give me permission to use this source code?

**Comment by NamelessOne** [comment]
Sure, you can use it. 
By the way, i think that code is not good. It is very old code and my first self-dependent project=) Also, all graphic resources and pictures made by my friend, and you can ask him for using that resources. His github account is https://github.com/serzilo
P.S. Sorry for my terrible English

**Comment by lovebdsobuj** [comment]
No no, your English is very good,

I test this application, this application support aac+, mp3 audio format.

What lib you used for aac+?

Actually commonly, I just see most of people used 'aacdecoder' lib for
support aac+ audio format.

Also your app have some others good features like, Program schedule
form Google calendar, Schedule Timer, Background play, Login etc.

That's why I think its a very nice development app for online Radio
station player!

**Comment by NamelessOne** [comment]
I use the bass audio library for audio streams decoding. 
Specifically for aac format i use bass_ac add-on. It's native library, now supported all 3 main android device processor architectures (armv5/armv7/x86). 
Here is the web-site of a library - http://www.un4seen.com/
